import dotenv from "dotenv";
dotenv.config();
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import {Server} from 'socket.io';
import {createServer} from 'http';
import * as XLSX from 'xlsx';
import PDFDocument from 'pdfkit';

const app=express(); const http=createServer(app);
const allowedOrigin=(origin,callback)=>{
 if(!origin || /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin) || origin===process.env.CLIENT_URL){return callback(null,true);}
 return callback(new Error('CORS origin not allowed'));
};
const io=new Server(http,{cors:{origin:allowedOrigin,methods:['GET','POST','PATCH','PUT','DELETE']}});
app.use(cors({origin:allowedOrigin})); app.use(express.json());
const uploadDir=path.resolve('uploads'); fs.mkdirSync(uploadDir,{recursive:true}); app.use('/uploads',express.static(uploadDir));
const upload=multer({dest:uploadDir});

const Employee=new mongoose.model('Employee',new mongoose.Schema({employeeId:{type:String,unique:true},name:String,email:String,role:String,department:String,team:String,status:{type:String,default:'Working'},attendance:{type:Number,default:100},project:String,manager:String,joiningDate:String,phone:String,type:{type:String,enum:['employee','intern'],default:'employee'}}));
const Attendance=new mongoose.model('Attendance',new mongoose.Schema({employeeId:String,date:String,checkIn:String,checkOut:String,checkInAt:Date,checkOutAt:Date,status:String,hours:{type:Number,default:0}}));
const Timesheet=new mongoose.model('Timesheet',new mongoose.Schema({employeeId:String,date:String,project:String,task:String,hours:Number,status:{type:String,default:'Submitted'},approvalStatus:{type:String,default:'Pending'},notes:String}));
const Project=new mongoose.model('Project',new mongoose.Schema({name:String,team:String,manager:String,progress:Number,deadline:String,status:String,members:[String],clientId:String}));
const Submission=new mongoose.model('Submission',new mongoose.Schema({employeeId:String,title:String,project:String,description:String,fileUrl:String,status:{type:String,default:'Under Review'},feedback:String,createdAt:{type:Date,default:Date.now}}));
const Leave=new mongoose.model('Leave',new mongoose.Schema({employeeId:String,type:String,from:String,to:String,reason:String,status:{type:String,default:'Pending'},createdAt:{type:Date,default:Date.now}}));
const Review=new mongoose.model('Review',new mongoose.Schema({employeeId:String,reviewer:String,period:String,rating:Number,feedback:String,status:{type:String,default:'Draft'},createdAt:{type:Date,default:Date.now}}));
const Schedule=new mongoose.model('Schedule',new mongoose.Schema({title:String,date:String,time:String,duration:String,team:String,employeeId:String,type:String}));
const Team=new mongoose.model('Team',new mongoose.Schema({name:{type:String,unique:true},lead:String,members:[String],projects:[String]}));
const Document=new mongoose.model('Document',new mongoose.Schema({name:String,category:String,fileUrl:String,employeeId:{type:String,default:'ALL'},team:String,projectId:String,uploadedBy:String,clientId:String,uploadedAt:{type:Date,default:Date.now}}));
const Task=new mongoose.model('Task',new mongoose.Schema({projectId:String,title:String,assigneeId:String,status:{type:String,default:'To Do'},priority:{type:String,default:'Medium'},dueDate:String}));
const Message=new mongoose.model('Message',new mongoose.Schema({teamId:String,fromId:String,fromName:String,toRole:String,toId:String,subject:String,text:String,createdAt:{type:Date,default:Date.now}}));
const Training=new mongoose.model('Training',new mongoose.Schema({title:String,description:String,completedBy:[String],skills:[String]}));
const Notification=new mongoose.model('Notification',new mongoose.Schema({employeeId:String,title:String,text:String,read:{type:Boolean,default:false},createdAt:{type:Date,default:Date.now}}));
const User=new mongoose.model('User',new mongoose.Schema({username:{type:String,unique:true},email:{type:String,unique:true,sparse:true},passwordHash:String,role:{type:String,enum:['admin','director','employee','intern']},employeeId:String,name:String,active:{type:Boolean,default:true},createdAt:{type:Date,default:Date.now}}));
const Client=new mongoose.model('Client',new mongoose.Schema({clientId:{type:String,unique:true},name:String,company:String,email:String,phone:String,industry:String,location:String,manager:String,status:{type:String,default:'Active'},notes:String,projects:[String],createdAt:{type:Date,default:Date.now}}));
const SystemConfig=new mongoose.model('SystemConfig',new mongoose.Schema({key:{type:String,unique:true},value:mongoose.Schema.Types.Mixed}));

const hashPassword=async(password)=>new Promise((resolve,reject)=>{const salt=crypto.randomBytes(16).toString('hex');crypto.scrypt(password,salt,64,(err,derived)=>{if(err)return reject(err);resolve(`${salt}:${derived.toString('hex')}`);});});
const verifyPassword=async(password,stored)=>new Promise((resolve,reject)=>{try{const [salt,key]=String(stored||'').split(':');if(!salt||!key)return resolve(false);crypto.scrypt(password,salt,64,(err,derived)=>{if(err)return reject(err);const a=Buffer.from(key,'hex');resolve(a.length===derived.length&&crypto.timingSafeEqual(a,derived));});}catch(e){reject(e);}});
const sessions=new Map();
const makeToken=()=>crypto.randomBytes(32).toString('hex');
const requireAuth=(req,res,next)=>{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const user=sessions.get(token);if(!user)return res.status(401).json({error:'Authentication required.'});req.user=user;next();};
const requireRole=(...allowed)=>(req,res,next)=>allowed.includes(req.user?.role)?next():res.status(403).json({error:'You do not have permission for this action.'});
const seedSystemUsers=async()=>{
 const admin=await User.findOne({username:'admin'}); if(!admin) await User.create({username:'admin',email:'admin@backbonehub.in',passwordHash:await hashPassword('admin123'),role:'admin',employeeId:'ADMIN',name:'Admin / HR'});
 const director=await User.findOne({username:'director'}); if(!director) await User.create({username:'director',email:'director@backbonehub.in',passwordHash:await hashPassword('director123'),role:'director',employeeId:'DIRECTOR',name:'Director'});
};
// Remove only the original demo records shipped with the prototype. New records created by Admin are preserved.
const removePrototypeData=async()=>{
 const marker=await SystemConfig.findOne({key:'prototypeCleanupV1'}); if(marker?.value?.done)return;
 const demoIds=['BH001','BH002','BH003','BH004','BH005'];
 const demoProjects=['Resume Intelligence','Employee Portal','Analytics Dashboard'];
 const demoClients=['CL001','CL002','CL003'];
 await Employee.deleteMany({employeeId:{$in:demoIds}});
 await User.deleteMany({employeeId:{$in:demoIds}});
 await Attendance.deleteMany({employeeId:{$in:demoIds}}); await Timesheet.deleteMany({employeeId:{$in:demoIds}}); await Submission.deleteMany({employeeId:{$in:demoIds}}); await Leave.deleteMany({employeeId:{$in:demoIds}}); await Review.deleteMany({employeeId:{$in:demoIds}}); await Notification.deleteMany({employeeId:{$in:demoIds}});
 await Team.deleteMany({name:{$in:['AI Team','Product Team','Data Team','HR Team']}});
 await Project.deleteMany({name:{$in:demoProjects},members:{$not:{$elemMatch:{$nin:demoIds}}}}); await Client.deleteMany({clientId:{$in:demoClients}});
 await Training.deleteMany({});
 await SystemConfig.updateOne({key:'prototypeCleanupV1'},{$set:{value:{done:true,at:new Date()}}},{upsert:true});
};

app.get('/api/health',(_,res)=>res.json({ok:true,service:'Backbonehub API'}));
app.post('/api/auth/login',async(req,res)=>{try{const {username,password}=req.body||{};if(!username||!password)return res.status(400).json({error:'Username and password are required.'});const user=await User.findOne({$or:[{username:String(username).toLowerCase()},{email:String(username).toLowerCase()}],active:true});if(!user||!(await verifyPassword(password,user.passwordHash)))return res.status(401).json({error:'Invalid username or password.'});const token=makeToken();const safe={id:String(user._id),username:user.username,email:user.email,role:user.role,employeeId:user.employeeId,name:user.name};sessions.set(token,safe);res.json({token,user:safe});}catch(err){console.error('Login error:',err);res.status(500).json({error:'Unable to login.'})}});
app.post('/api/auth/change-password',requireAuth,async(req,res)=>{const {currentPassword,newPassword}=req.body||{};const user=await User.findById(req.user.id);if(!user||!(await verifyPassword(currentPassword,user.passwordHash)))return res.status(400).json({error:'Current password is incorrect.'});if(!newPassword||newPassword.length<8)return res.status(400).json({error:'New password must be at least 8 characters.'});user.passwordHash=await hashPassword(newPassword);await user.save();res.json({ok:true});});
app.use('/api',requireAuth);
app.get('/api/employees',async(req,res)=>{const q=req.query.q||'';let filter={};if(req.user.role!=='admin'&&req.user.role!=='director')filter={employeeId:req.user.employeeId};if(q)filter={$and:[filter,{$or:[{name:new RegExp(q,'i')},{email:new RegExp(q,'i')},{team:new RegExp(q,'i')},{role:new RegExp(q,'i')}]}]};res.json(await Employee.find(filter).sort({name:1}));});
app.get('/api/employees/by-employee-id/:employeeId',async(req,res)=>{if(!['admin','director'].includes(req.user.role)&&req.params.employeeId!==req.user.employeeId)return res.status(403).json({error:'You can only access your own profile.'});const e=await Employee.findOne({employeeId:req.params.employeeId});if(!e)return res.status(404).json({error:'Employee not found'});res.json(e)});
app.post('/api/employees',requireRole('admin'),async(req,res)=>{try{const body={...req.body};if(!body.employeeId){const last=await Employee.findOne({employeeId:/^BH\d+$/}).sort({employeeId:-1});const next=last?Number(last.employeeId.slice(2))+1:1;body.employeeId=`BH${String(next).padStart(3,'0')}`;}if(!body.username||!body.password)return res.status(400).json({error:'Username and password are required.'});const e=await Employee.create(body);const username=String(body.username).trim().toLowerCase();await User.create({username,email:e.email,passwordHash:await hashPassword(body.password),role:e.type==='intern'?'intern':'employee',employeeId:e.employeeId,name:e.name});if(e.team){const team=await Team.findOne({name:e.team});if(team&&!team.members.includes(e.employeeId)){team.members.push(e.employeeId);await team.save();}}if(e.project){const project=await Project.findOne({name:e.project});if(project&&!project.members.includes(e.employeeId)){project.members.push(e.employeeId);await project.save();}}res.status(201).json(e)}catch(err){res.status(400).json({error:err.message})}});
app.patch('/api/employees/:id',requireRole('admin'),async(req,res)=>{try{const key=req.params.id;const filter=/^[0-9a-fA-F]{24}$/.test(key)?{_id:key}:{employeeId:key};const before=await Employee.findOne(filter);if(!before)return res.status(404).json({error:'Employee not found'});const e=await Employee.findOneAndUpdate(filter,req.body,{new:true,runValidators:true});if(before.team!==e.team){if(before.team){const old=await Team.findOne({name:before.team});if(old){old.members=old.members.filter(x=>x!==e.employeeId);await old.save();}}if(e.team){const next=await Team.findOne({name:e.team});if(next&&!next.members.includes(e.employeeId)){next.members.push(e.employeeId);await next.save();}}}if(req.body.project!==undefined&&before.project!==e.project){if(before.project){const oldProject=await Project.findOne({name:before.project});if(oldProject){oldProject.members=oldProject.members.filter(x=>x!==e.employeeId);await oldProject.save();}}if(e.project){const newProject=await Project.findOne({name:e.project});if(newProject&&!newProject.members.includes(e.employeeId)){newProject.members.push(e.employeeId);await newProject.save();}}}if(req.body.email||req.body.name){await User.updateOne({employeeId:e.employeeId},{$set:{email:e.email,name:e.name}});}res.json(e)}catch(err){res.status(400).json({error:err.message})}});
app.patch('/api/employees/by-employee-id/:employeeId',async(req,res)=>{if(req.user.role!=='admin'&&req.user.employeeId!==req.params.employeeId)return res.status(403).json({error:'You can only edit your own profile.'});const current=await Employee.findOne({employeeId:req.params.employeeId});if(!current)return res.status(404).json({error:'Employee not found'});const oldTeam=current.team;const body=req.user.role==='admin'?req.body:{name:req.body.name,email:req.body.email,phone:req.body.phone};const e=await Employee.findOneAndUpdate({employeeId:req.params.employeeId},body,{new:true,runValidators:true});if(body.team!==undefined&&req.body.team!==oldTeam){if(oldTeam){const old=await Team.findOne({name:oldTeam});if(old){old.members=old.members.filter(x=>x!==e.employeeId);await old.save();}}if(req.body.team){const next=await Team.findOne({name:req.body.team});if(next&&!next.members.includes(e.employeeId)){next.members.push(e.employeeId);await next.save();}}}if(body.email||body.name)await User.updateOne({employeeId:e.employeeId},{$set:{email:e.email,name:e.name}});res.json(e)});
app.delete('/api/employees/:id',requireRole('admin'),async(req,res)=>{try{const key=req.params.id;const filter=/^[0-9a-fA-F]{24}$/.test(key)?{_id:key}:{employeeId:key};const e=await Employee.findOne(filter);if(!e)return res.status(404).json({error:'Employee not found'});await Team.updateMany({},{$pull:{members:e.employeeId}});await Project.updateMany({members:e.employeeId},{$pull:{members:e.employeeId}});await Promise.all([Attendance.deleteMany({employeeId:e.employeeId}),Timesheet.deleteMany({employeeId:e.employeeId}),Submission.deleteMany({employeeId:e.employeeId}),Leave.deleteMany({employeeId:e.employeeId}),Review.deleteMany({employeeId:e.employeeId}),Notification.deleteMany({employeeId:e.employeeId}),Document.deleteMany({employeeId:e.employeeId}),Task.deleteMany({assigneeId:e.employeeId}),Schedule.deleteMany({employeeId:e.employeeId}),Message.deleteMany({fromId:e.employeeId}),Employee.deleteOne({_id:e._id}),User.deleteMany({employeeId:e.employeeId})]);res.json({ok:true})}catch(err){res.status(400).json({error:err.message})}});
app.get('/api/dashboard',async(req,res)=>{if(req.user.role==='admin'){const [total,present,pending,projects]=await Promise.all([Employee.countDocuments(),Attendance.countDocuments({status:'Present'}),Timesheet.countDocuments({approvalStatus:'Pending'}),Project.countDocuments({status:{$ne:'Completed'}})]);return res.json({total,present,pending,projects});}if(req.user.role==='director')return res.status(403).json({error:'Director dashboard is disabled.'});const id=req.user.employeeId;const [att,times,projects,subs,notifications]=await Promise.all([Attendance.find({employeeId:id}),Timesheet.find({employeeId:id}),Project.find({members:id}),Submission.find({employeeId:id}),Notification.find({$or:[{employeeId:id},{employeeId:'ALL'}]}).sort({createdAt:-1}).limit(10)]);const present=att.filter(x=>x.status==='Present').length;const hours=times.reduce((a,x)=>a+(Number(x.hours)||0),0)+att.reduce((a,x)=>a+(Number(x.hours)||0),0);res.json({attendance:Math.round((present/Math.max(att.length,1))*100),hours,projects:projects.length,submissions:subs.length,notifications});});
app.get('/api/attendance/:employeeId',async(req,res)=>{if(!['admin','director'].includes(req.user.role)&&req.params.employeeId!==req.user.employeeId)return res.status(403).json({error:'You can only access your own attendance.'});res.json(await Attendance.find({employeeId:req.params.employeeId}).sort({date:-1}));});
const getIndiaNow=()=>{const now=new Date();const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return {now,date:`${map.year}-${map.month}-${map.day}`,time:now.toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true})};};
const parseIndiaTime=(date,time)=>{if(!date||!time)return null;const m=String(time).trim().match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)$/i);if(!m)return null;let h=Number(m[1]);const min=Number(m[2]);const sec=Number(m[3]||0);const ap=m[4].toUpperCase();if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;return new Date(`${date}T${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}+05:30`);};
const repairLegacyAttendance=async()=>{const docs=await Attendance.find({$or:[{checkInAt:{$exists:false}},{checkOut:{$exists:true},checkOutAt:{$exists:false}}]});for(const a of docs){let changed=false;if(!a.checkInAt&&a.checkIn){const d=parseIndiaTime(a.date,a.checkIn);if(d){a.checkInAt=d;changed=true;}}if(a.checkOut&&!a.checkOutAt){const d=parseIndiaTime(a.date,a.checkOut);if(d){a.checkOutAt=d;changed=true;}}if(a.checkInAt&&a.checkOutAt){const h=Math.max(0,(a.checkOutAt.getTime()-a.checkInAt.getTime())/3600000);a.hours=Math.round(h*100)/100;changed=true;}else if(a.checkInAt&&!a.checkOutAt){a.hours=0;changed=true;}if(changed)await a.save();}};
app.post('/api/attendance/checkin',async(req,res)=>{try{const employeeId=['admin','director'].includes(req.user.role)?req.body.employeeId:req.user.employeeId;if(!employeeId)return res.status(400).json({error:'Employee ID is required.'});const {now,date,time}=getIndiaNow();const open=await Attendance.findOne({employeeId,date,checkInAt:{$exists:true},checkOutAt:{$exists:false}}).sort({checkInAt:-1});if(open)return res.status(400).json({error:'You are already clocked in.',attendance:open});const a=await Attendance.create({employeeId,date,status:'Present',checkIn:time,checkInAt:now,hours:0});res.json(a)}catch(err){console.error('Check-in error:',err);res.status(400).json({error:err.message})}});
app.post('/api/attendance/checkout',async(req,res)=>{try{const employeeId=['admin','director'].includes(req.user.role)?req.body.employeeId:req.user.employeeId;if(!employeeId)return res.status(400).json({error:'Employee ID is required.'});const {now,date,time}=getIndiaNow();const a=await Attendance.findOne({employeeId,date,checkInAt:{$exists:true},checkOutAt:{$exists:false}}).sort({checkInAt:-1});if(!a)return res.status(404).json({error:'No active check-in found for today. Please clock in first.'});const durationMs=now.getTime()-new Date(a.checkInAt).getTime();if(durationMs<0)return res.status(400).json({error:'Invalid check-out time.'});a.checkOut=time;a.checkOutAt=now;a.hours=Math.round((durationMs/3600000)*100)/100;await a.save();res.json(a)}catch(err){console.error('Check-out error:',err);res.status(400).json({error:err.message})}});
app.post('/api/timesheets',async(req,res)=>{const employeeId=req.user.role==='admin'?req.body.employeeId:req.user.employeeId;const t=await Timesheet.create({...req.body,employeeId});await Notification.create({employeeId:'ADMIN',title:'New timesheet',text:`${t.employeeId} submitted ${t.hours} hours`});io.emit('notification',{title:'New timesheet submitted',text:`${t.employeeId} needs review`});res.status(201).json(t)});
app.get('/api/timesheets',async(req,res)=>{const filter=req.user.role==='admin'?req.query:{employeeId:req.user.employeeId};res.json(await Timesheet.find(filter).sort({date:-1}))});
app.patch('/api/timesheets/:id',async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Only Admin can review timesheets.'});const t=await Timesheet.findByIdAndUpdate(req.params.id,req.body,{new:true});if(t&&req.body.approvalStatus){await Notification.create({employeeId:t.employeeId,title:`Timesheet ${req.body.approvalStatus}`,text:`Your timesheet was ${req.body.approvalStatus.toLowerCase()}.`});}res.json(t)});
app.get('/api/projects',async(req,res)=>{const filter=req.user.role==='admin'?{}:{members:req.user.employeeId};res.json(await Project.find(filter).sort({name:1}))});
app.post('/api/projects',requireRole('admin'),async(req,res)=>{try{const p=await Project.create({...req.body,members:req.body.members||[]});if(p.team)await Team.updateOne({name:p.team},{$addToSet:{projects:p.name}});res.status(201).json(p)}catch(err){res.status(400).json({error:err.message})}});
app.patch('/api/projects/:id',requireRole('admin'),async(req,res)=>{try{const before=await Project.findById(req.params.id);if(!before)return res.status(404).json({error:'Project not found'});const p=await Project.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(req.body.team!==undefined&&before.team!==p.team){if(before.team)await Team.updateOne({name:before.team},{$pull:{projects:before.name}});if(p.team)await Team.updateOne({name:p.team},{$addToSet:{projects:p.name}});}res.json(p)}catch(err){res.status(400).json({error:err.message})}});
app.delete('/api/projects/:id',requireRole('admin'),async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({error:'Project not found'});await Promise.all([Task.deleteMany({projectId:String(p._id)}),Document.deleteMany({projectId:String(p._id)}),Team.updateMany({},{$pull:{projects:p.name}}),Project.deleteOne({_id:p._id})]);res.json({ok:true})});
app.get('/api/tasks',async(req,res)=>{const filter=req.user.role==='admin'?req.query:{assigneeId:req.user.employeeId};res.json(await Task.find(filter).sort({dueDate:1}));});app.post('/api/tasks',async(req,res)=>{if(req.user.role!=='admin'&&req.body.assigneeId!==req.user.employeeId)return res.status(403).json({error:'You can only create tasks for yourself.'});const p=await Project.findById(req.body.projectId);if(!p||(!p.members?.includes(req.user.employeeId)&&req.user.role!=='admin'))return res.status(403).json({error:'You are not a member of this project.'});res.status(201).json(await Task.create(req.body))});app.patch('/api/tasks/:id',async(req,res)=>res.json(await Task.findByIdAndUpdate(req.params.id,req.body,{new:true})));

app.post('/api/submissions/upload',upload.single('file'),async(req,res)=>{const employeeId=req.user.role==='admin'?req.body.employeeId:req.user.employeeId;const s=await Submission.create({employeeId,title:req.body.title,project:req.body.project,description:req.body.description,fileUrl:req.file?`/uploads/${req.file.filename}`:''});io.emit('notification',{title:'New work submission',text:s.title});res.status(201).json(s)});
app.get('/api/submissions',async(req,res)=>{const filter=req.user.role==='admin'?req.query:{employeeId:req.user.employeeId};res.json(await Submission.find(filter).sort({createdAt:-1}))});app.post('/api/submissions',async(req,res)=>{const employeeId=req.user.role==='admin'?req.body.employeeId:req.user.employeeId;res.status(201).json(await Submission.create({...req.body,employeeId}))});app.patch('/api/submissions/:id',async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Only Admin can review submissions.'});const sub=await Submission.findByIdAndUpdate(req.params.id,req.body,{new:true});res.json(sub)});
app.get('/api/leaves',async(req,res)=>{const filter=req.user.role==='admin'?req.query:{employeeId:req.user.employeeId};res.json(await Leave.find(filter).sort({createdAt:-1}));});
app.post('/api/leaves',async(req,res)=>{try{const body={...req.body,employeeId:req.user.role==='admin'?req.body.employeeId:req.user.employeeId};if(!body.employeeId||!body.from||!body.to||!body.type)return res.status(400).json({error:'Employee, leave type, start date and end date are required.'});if(new Date(body.to)<new Date(body.from))return res.status(400).json({error:'End date cannot be before start date.'});const leave=await Leave.create(body);await Notification.create({employeeId:'ADMIN',title:'New leave request',text:`${leave.employeeId} requested ${leave.type} leave from ${leave.from} to ${leave.to}.`});io.emit('notification',{employeeId:'ADMIN',title:'New leave request',text:`${leave.employeeId} requested ${leave.type} leave from ${leave.from} to ${leave.to}.`});res.status(201).json(leave)}catch(err){res.status(400).json({error:err.message})}});
app.patch('/api/leaves/:id',async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Only Admin can approve leave.'});try{const leave=await Leave.findByIdAndUpdate(req.params.id,req.body,{new:true});if(!leave)return res.status(404).json({error:'Leave request not found.'});if(req.body.status){await Notification.create({employeeId:leave.employeeId,title:`Leave ${req.body.status}`,text:`Your ${leave.type} leave request (${leave.from} to ${leave.to}) was ${req.body.status.toLowerCase()}.`});io.emit('notification',{employeeId:leave.employeeId,title:`Leave ${req.body.status}`,text:`Your ${leave.type} leave request was ${req.body.status.toLowerCase()}.`});}res.json(leave)}catch(err){res.status(400).json({error:err.message})}});
app.get('/api/schedules',async(req,res)=>{if(req.user.role==='admin')return res.json(await Schedule.find().sort({date:1,time:1}));res.json(await Schedule.find({$or:[{employeeId:req.user.employeeId},{team:req.user.team||'__none__'}]}).sort({date:1,time:1}));}); app.post('/api/schedules',requireRole('admin'),async(req,res)=>res.status(201).json(await Schedule.create(req.body)));
app.get('/api/teams',async(req,res)=>{let teams;if(req.user.role==='admin')teams=await Team.find().sort({name:1}).lean();else{const e=await Employee.findOne({employeeId:req.user.employeeId});if(!e?.team)return res.json([]);teams=await Team.find({name:e.team}).lean();}const ids=[...new Set(teams.flatMap(t=>t.members||[]))];const people=await Employee.find({employeeId:{$in:ids}}).select('employeeId name role type').lean();const byId=Object.fromEntries(people.map(p=>[p.employeeId,p]));res.json(teams.map(t=>({...t,memberDetails:(t.members||[]).map(id=>byId[id]).filter(Boolean)})));});app.post('/api/teams',requireRole('admin'),async(req,res)=>res.status(201).json(await Team.create(req.body)));app.patch('/api/teams/:id',requireRole('admin'),async(req,res)=>res.json(await Team.findByIdAndUpdate(req.params.id,req.body,{new:true})));app.delete('/api/teams/:id',requireRole('admin'),async(req,res)=>{const t=await Team.findById(req.params.id);if(!t)return res.status(404).json({error:'Team not found'});await Employee.updateMany({team:t.name},{$set:{team:''}});await Team.deleteOne({_id:t._id});res.json({ok:true})});
app.get('/api/training',async(_,res)=>res.json(await Training.find())); app.patch('/api/training/:id/complete',async(req,res)=>{const t=await Training.findById(req.params.id);if(!t)return res.status(404).json({error:'Training not found'});const id=req.user.role==='admin'?req.body.employeeId:req.user.employeeId;if(!t.completedBy.includes(id))t.completedBy.push(id);await t.save();res.json(t)});
app.post('/api/notifications',async(req,res)=>{const n=await Notification.create(req.body);io.emit('notification',{title:n.title,text:n.text});res.status(201).json(n)});
app.post('/api/messages',async(req,res)=>{try{let body={...req.body};if(body.teamId&&req.user.role!=='admin'){const e=await Employee.findOne({employeeId:req.user.employeeId});const t=await Team.findById(body.teamId);if(!e?.team||!t||e.team!==t.name||!t.members.includes(req.user.employeeId))return res.status(403).json({error:'You can only chat with your own team.'});body.fromId=req.user.employeeId;}if(body.teamId&&req.user.role==='admin')body.fromId=req.body.fromId||'ADMIN';const sender=await Employee.findOne({employeeId:body.fromId});body.fromName=sender?.name||req.user.name||body.fromId;const m=await Message.create(body);if(m.teamId)io.emit('team-message',m);else io.emit('message',{subject:m.subject,text:m.text});res.status(201).json(m)}catch(err){res.status(400).json({error:err.message})}}); app.get('/api/messages',async(req,res)=>{if(req.query.teamId&&req.user.role!=='admin'){const e=await Employee.findOne({employeeId:req.user.employeeId});const t=await Team.findById(req.query.teamId);if(!e?.team||!t||e.team!==t.name||!t.members.includes(req.user.employeeId))return res.status(403).json({error:'You can only access your own team chat.'});}const filter=req.query.teamId?{teamId:req.query.teamId}:req.query.toId?{toId:req.query.toId}:{};res.json(await Message.find(filter).sort({createdAt:1}));});
app.get('/api/notifications/:employeeId',async(req,res)=>{if(req.user.role!=='admin'&&req.params.employeeId!==req.user.employeeId)return res.status(403).json({error:'Forbidden'});res.json(await Notification.find({$or:[{employeeId:req.params.employeeId},{employeeId:'ALL'}]}).sort({createdAt:-1}).limit(30));});
app.patch('/api/notifications/:id/read',async(req,res)=>res.json(await Notification.findByIdAndUpdate(req.params.id,{read:true},{new:true})));
app.post('/api/documents',requireRole('admin'),upload.single('file'),async(req,res)=>{const d=await Document.create({name:req.file?.originalname||req.body.name,category:req.body.category||'General',employeeId:req.body.employeeId||'ALL',team:req.body.team||'',projectId:req.body.projectId||'',clientId:req.body.clientId||'',uploadedBy:req.user.name||req.user.username||'ADMIN',fileUrl:req.file?`/uploads/${req.file.filename}`:''});io.emit('notification',{title:'New document published',text:d.name});res.status(201).json(d)});
app.get('/api/documents',async(req,res)=>{if(req.query.projectId){const p=await Project.findById(req.query.projectId);if(req.user.role!=='admin'&&req.user.role!=='director'&&(!p||!p.members.includes(req.user.employeeId)))return res.status(403).json({error:'You do not have access to this project.'});return res.json(await Document.find({projectId:req.query.projectId}).sort({uploadedAt:-1}));}if(req.user.role==='admin'||req.user.role==='director')return res.json(await Document.find().sort({uploadedAt:-1}));const e=await Employee.findOne({employeeId:req.user.employeeId});const filters=[{employeeId:'ALL'},{employeeId:req.user.employeeId}];if(e?.team)filters.push({team:e.team});res.json(await Document.find({$or:filters}).sort({uploadedAt:-1}));});
app.get('/api/director/people',requireRole('director','admin'),async(req,res)=>{const people=await Employee.find().sort({name:1}).lean();const ids=people.map(p=>p.employeeId);const [attendance,leaves,timesheets,submissions,docs]=await Promise.all([Attendance.find({employeeId:{$in:ids}}).sort({date:-1}).lean(),Leave.find({employeeId:{$in:ids}}).sort({createdAt:-1}).lean(),Timesheet.find({employeeId:{$in:ids}}).sort({date:-1}).lean(),Submission.find({employeeId:{$in:ids}}).sort({createdAt:-1}).lean(),Document.find({employeeId:{$in:ids}}).sort({uploadedAt:-1}).lean()]);const map={};for(const p of people)map[p.employeeId]={employee:p,attendance:attendance.filter(x=>x.employeeId===p.employeeId),leaves:leaves.filter(x=>x.employeeId===p.employeeId),timesheets:timesheets.filter(x=>x.employeeId===p.employeeId),submissions:submissions.filter(x=>x.employeeId===p.employeeId),documents:docs.filter(x=>x.employeeId===p.employeeId||x.employeeId==='ALL'||(x.team&&x.team===p.team))};res.json(Object.values(map));});
app.get('/api/clients',requireRole('director','admin'),async(_,res)=>res.json(await Client.find().sort({name:1})));
app.post('/api/clients',requireRole('admin','director'),async(req,res)=>{try{const body={...req.body};if(!body.clientId){const last=await Client.findOne({clientId:/^CL\\d+$/}).sort({clientId:-1});const next=last?Number(last.clientId.slice(2))+1:1;body.clientId=`CL${String(next).padStart(3,'0')}`;}res.status(201).json(await Client.create(body));}catch(err){res.status(400).json({error:err.message})}});
app.patch('/api/clients/:id',requireRole('admin','director'),async(req,res)=>res.json(await Client.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})));
app.get('/api/clients/:id/details',requireRole('director','admin'),async(req,res)=>{const c=await Client.findById(req.params.id).lean();if(!c)return res.status(404).json({error:'Client not found'});const projects=await Project.find({$or:[{name:{$in:c.projects||[]}},{clientId:String(c._id)}]}).lean();const projectIds=projects.map(p=>String(p._id));const docs=await Document.find({clientId:String(c._id)}).sort({uploadedAt:-1}).lean();const projectDocs=projectIds.length?await Document.find({projectId:{$in:projectIds}}).sort({uploadedAt:-1}).lean():[];res.json({client:c,projects,documents:[...docs,...projectDocs]})});
app.get('/api/export/employees',async(_,res)=>{const data=await Employee.find().lean();const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Employees');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition','attachment; filename=backbonehub-employees.xlsx');res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buf)});
app.get('/api/export/attendance',async(_,res)=>{const data=await Attendance.find().lean();const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Attendance');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition','attachment; filename=backbonehub-attendance.xlsx');res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buf)});
app.get('/api/export/employees.pdf',async(_,res)=>{const data=await Employee.find().lean();const doc=new PDFDocument({margin:40});res.setHeader('Content-Disposition','attachment; filename=backbonehub-employees.pdf');res.type('application/pdf');doc.pipe(res);doc.fontSize(20).text('Backbonehub.in - Employee Report');doc.moveDown();doc.fontSize(10);data.forEach((e,i)=>doc.text(`${i+1}. ${e.employeeId} | ${e.name} | ${e.role} | ${e.team||''} | ${e.status||''} | Attendance: ${e.attendance||0}%`));doc.end()});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error'})});

io.on('connection',socket=>socket.emit('connected',{message:'Backbonehub live notifications connected'}));
process.env.PORT || 5000
mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/backbonehub').then(async()=>{console.log('MongoDB connected');await removePrototypeData();await seedSystemUsers();await repairLegacyAttendance();console.log('Prototype demo data removed; attendance records checked and legacy times repaired.');http.listen(port,()=>console.log(`Backbonehub API: http://localhost:${port}`));}).catch(err=>{console.error('MongoDB connection failed:',err.message);console.error('Start MongoDB and run npm run server again.');process.exit(1)});
